apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: postgresql
  spec:
    lookupPolicy:
      local: true
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: postgresql
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: postgresql:latest
    source:
      git:
        uri: https://gitlab.bbguimaraes.com/bbguimaraes/openshift-deployments.git
      contextDir: postgresql
      type: Git
    strategy:
      type: Docker
    triggers: []
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: postgresql
    labels:
      app: postgresql
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: postgresql
      spec:
        containers:
        - name: postgresql
          image: ' '
          ports:
          - containerPort: 5432
            protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
          - name: run
            mountPath: /run/postgresql
          - name: varlib
            mountPath: /var/lib/postgresql
          livenessProbe:
            tcpSocket:
              port: 5432
          readinessProbe:
            exec:
              command: ["/usr/local/bin/wrapper.sh", "psql", "-c", ""]
        volumes:
        - name: run
          emptyDir:
            medium: Memory
        - name: varlib
          emptyDir:
            medium: Memory
    triggers:
    - type: ImageChange
      imageChangeParams:
        containerNames:
        - postgresql
        from:
          kind: ImageStreamTag
          name: postgresql:latest
- apiVersion: v1
  kind: Service
  metadata:
    name: postgresql
  spec:
    ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: postgresql
    type: ClusterIP
