apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: postgresql
  spec:
    lookupPolicy:
      local: true
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: memcached
  spec:
    lookupPolicy:
      local: true
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: php
  spec:
    lookupPolicy:
      local: true
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: nginx
  spec:
    lookupPolicy:
      local: true
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: postgresql
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: postgresql:latest
    source:
      type: Git
      contextDir: nextcloud/postgresql
      git:
        uri: https://gitlab.bbguimaraes.com/bbguimaraes/openshift-deployments.git
      type: Docker
    triggers: []
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: memcached
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: memcached:latest
    source:
      type: Git
      contextDir: nextcloud/memcached
      git:
        uri: https://gitlab.bbguimaraes.com/bbguimaraes/openshift-deployments.git
    strategy:
      type: Docker
    triggers: []
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: php
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: php:latest
    source:
      type: Git
      contextDir: nextcloud/php
      git:
        uri: https://gitlab.bbguimaraes.com/bbguimaraes/openshift-deployments.git
    strategy:
      type: Docker
    triggers: []
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: nginx
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: nginx:latest
    source:
      type: Git
      contextDir: nextcloud/nginx
      git:
        uri: https://gitlab.bbguimaraes.com/bbguimaraes/openshift-deployments.git
    strategy:
      type: Docker
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: postgresql
    labels:
      nextcloud: postgresql
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          nextcloud: postgresql
      spec:
        containers:
        - name: postgresql
          image: ' '
          ports:
          - containerPort: 5432
            protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
          - name: run
            mountPath: /run/postgresql
          - name: varlib
            mountPath: /var/lib/postgresql
          livenessProbe:
            exec:
              command: ["/usr/local/bin/wrapper.sh", "psql", "-c", ""]
          readinessProbe:
            tcpSocket:
              port: 5432
        volumes:
        - name: run
          emptyDir:
            medium: Memory
        - name: varlib
          emptyDir:
            medium: Memory
    triggers:
    - type: ImageChange
      imageChangeParams:
        containerNames:
        - postgresql
        from:
          kind: ImageStreamTag
          name: postgresql:latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: memcached
    labels:
      nextcloud: memcached
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          nextcloud: memcached
      spec:
        containers:
        - name: memcached
          image: ' '
          ports:
          - containerPort: 11211
            protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
          livenessProbe:
            tcpSocket:
              port: 11211
          readinessProbe:
            exec:
              command:
              - memcached-tool
              - localhost:11211
              - stats
    triggers:
    - type: ImageChange
      imageChangeParams:
        containerNames:
        - memcached
        from:
          kind: ImageStreamTag
          name: memcached:latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: php
    labels:
      nextcloud: php
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          nextcloud: php
      spec:
        containers:
        - name: php
          image: ' '
          ports:
          - containerPort: 8000
            protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
          - name: tmp
            mountPath: /tmp
          - name: pkg
            mountPath: /usr/share/nextcloud
          readinessProbe:
            tcpSocket:
              port: 8000
          livenessProbe:
            tcpSocket:
              port: 8000
        volumes:
        - name: tmp
          emptyDir:
            medium: Memory
        - name: pkg
          emptyDir:
            medium: Memory
    triggers:
    - type: ImageChange
      imageChangeParams:
        containerNames:
        - php
        from:
          kind: ImageStreamTag
          name: php:latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: nginx
    labels:
      nextcloud: nginx
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          nextcloud: nginx
      spec:
        containers:
        - name: nginx
          image: ' '
          ports:
          - containerPort: 8000
            protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
          - name: varlib
            mountPath: /var/lib/nginx
          - name: run
            mountPath: /run/nginx
          - name: pkg
            mountPath: /usr/share/nextcloud
          livenessProbe:
            tcpSocket:
              port: 8000
          readinessProbe:
            exec:
              command:
              - curl
              - --silent
              - --show-error
              - --fail
              - localhost:8000/status.php
        volumes:
        - name: varlib
          emptyDir:
            medium: Memory
        - name: run
          emptyDir:
            medium: Memory
        - name: pkg
          emptyDir:
            medium: Memory
    triggers:
    - type: ImageChange
      imageChangeParams:
        containerNames:
        - nginx
        from:
          kind: ImageStreamTag
          name: nginx:latest
- apiVersion: v1
  kind: Service
  metadata:
    name: postgresql
  spec:
    ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      gitlab: postgresql
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: memcached
  spec:
    ports:
    - name: 11211-tcp
      port: 11211
      protocol: TCP
      targetPort: 11211
    selector:
      gitlab: memcached
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: php
  spec:
    ports:
    - name: 8000-tcp
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      gitlab: php
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: nginx
  spec:
    ports:
    - name: 8000-tcp
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      gitlab: nginx
    type: ClusterIP
