apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: static
  spec:
    lookupPolicy:
      local: true
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: static
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: static:latest
    source:
      type: Git
      git:
        uri: https://gitlab.bbguimaraes.com/bbguimaraes/openshift-deployments.git
      contextDir: static/nginx
    strategy:
      type: Docker
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: static
    labels:
      static: nginx
  spec:
    replicas: 1
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          static: nginx
      spec:
        containers:
        - name: nginx
          image: ' '
          ports:
          - containerPort: 8000
            protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
          livenessProbe:
            tcpSocket:
              port: 8000
          volumeMounts:
          - name: run
            mountPath: /run/nginx
          - name: varlib
            mountPath: /var/lib/nginx
          - name: srv
            mountPath: /srv/http
        volumes:
        - name: run
          emptyDir:
            medium: Memory
        - name: varlib
          emptyDir:
            medium: Memory
        - name: srv
          emptyDir:
            medium: Memory
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: false
        from:
          kind: ImageStreamTag
          name: static:latest
        containerNames:
        - nginx
- apiVersion: v1
  kind: Service
  metadata:
    name: static
  spec:
    selector:
      static: nginx
    ports:
    - name: 8000-tcp
      port: 8000
      targetPort: 8000
      protocol: TCP
